### ISSUE TITLE
Landing Page

### ISSUE THREAD

**Issue by sydney-c7** [budget-munchies/budget-munchies-project#2]
Please do work for this task in a branch named issue-2.

- "Budget Munchies" Title
- Displaying the background image
- Category buttons (breakfast, lunch, dinner, dessert, snack, etc.)
- Grid with cards of popular recipes (name, description, photo, likes, link to recipe page)

**Comment by marissahalim** [comment]
Didn't do the category buttons
Still need to add links and tags (need to research how)
